<a href="https://colab.research.google.com/github/sahil3Vedi/Self-Driving-Car-Arduino/blob/master/Convert_txt_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
import pandas as pd
import os
drive.mount('/content/drive')
import numpy as np

In [0]:
DATA_DIR = 'drive/My Drive/Self Driving'
TXT_FILE = 'T_LOG.TXT'
FILE_PATH = os.path.join(DATA_DIR,TXT_FILE)

with open(FILE_PATH, 'r') as file:
    data = file.read()

print(data)

##### SMART CAR DATA-LOG #####

>> TRAINING DATA LOG : 
#Front Sensor Data : 333 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).

>> TRAINING DATA LOG : 
#Front Sensor Data : 331 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).

>> TRAINING DATA LOG : 
#Front Sensor Data : 324 cm
#Left Sensor Data  : 3 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).

>> TRAINING DATA LOG : 
#Front Sensor Data : 301 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 3 cm
#User Command Received : Go Straight (Default).

>> TRAINING DATA LOG : 
#Front Sensor Data : 283 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).

>> TRAINING DATA LOG : 
#Front Sensor Data : 240 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).

>> TRAINING DATA LOG : 
#Front Sensor Data : 237 c

In [0]:
#Splitting TXT
dataSplit = data.split('\n')
#removing blank lines
while("" in dataSplit) : 
  dataSplit.remove("")
#removing first line
dataSplit.pop(0)

for each_element in dataSplit:
  if each_element[0] == ">":
    dataSplit.remove(each_element)
#printing contents of the array
for elements in dataSplit:
  print(elements)

#Front Sensor Data : 333 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).
#Front Sensor Data : 331 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).
#Front Sensor Data : 324 cm
#Left Sensor Data  : 3 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).
#Front Sensor Data : 301 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 3 cm
#User Command Received : Go Straight (Default).
#Front Sensor Data : 283 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).
#Front Sensor Data : 240 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 4 cm
#User Command Received : Go Straight (Default).
#Front Sensor Data : 237 cm
#Left Sensor Data  : 66 cm
#Right Sensor Data : 276 cm
#User Command Received : Turn "LEFT".
#Front Sensor Data : 207 cm
#Left Sensor Data  : 4 cm
#Right Sensor Data : 207 cm
#User Command Received : Go S

In [0]:
#Creating Training and Testing Vectors:
X_TRAIN = []
Y_TRAIN = []

X_sample = []
for i in range(len(dataSplit)):
  if((i+1)%4==0):
    reading = dataSplit[i].split(':')
    temp = reading[1]
    actual_reading = temp[1:-1]
    final_reading = actual_reading.split(" ")
    Y_value = 0
    if '"LEFT"' in final_reading:
      Y_value = -1
    if '"RIGHT"' in final_reading:
      Y_value = 1
    Y_TRAIN.append(Y_value)
    X_TRAIN.append(X_sample)
    X_sample=[]
  else:
    reading = dataSplit[i].split(':')
    actual_reading = reading[1]
    final_reading = actual_reading[1:-3]
    X_sample.append(int(final_reading))

numpy_X = [np.asarray(k) for k in X_TRAIN]
NPX = np.asarray(numpy_X)

numpy_Y = []
for j in Y_TRAIN:
  if j==-1:
    subArr=[1,0,0]
  elif j==0:
    subArr=[0,1,0]
  else:
    subArr=[0,0,1]
  tempArr = np.asarray(subArr)
  numpy_Y.append(tempArr)
NPY = np.asarray(numpy_Y)


print(NPX)
print(NPY)
print(len(NPX))
print(len(NPY))

[[ 333    4    4]
 [ 331    4    4]
 [ 324    3    4]
 [ 301    4    3]
 [ 283    4    4]
 [ 240    4    4]
 [ 237   66  276]
 [ 207    4  207]
 [ 178    4    3]
 [2488    3    3]
 [ 188    3    3]
 [ 108    3    3]
 [  79    6    3]
 [  56    7    6]
 [  76    7    8]
 [ 196    4   30]
 [ 165    5    5]
 [ 136    4    5]
 [ 113    0    4]
 [ 275    4    4]
 [ 241    4    3]
 [ 208    4    3]
 [ 181    4    4]
 [ 289    3    3]
 [ 218    4    4]
 [ 173    4    4]
 [ 136    7  106]
 [ 110    4  220]
 [ 114    5    4]
 [2425    4  117]
 [2482    4    3]
 [ 197    4    4]
 [2508    4    3]
 [ 141    3    3]
 [ 104    3    4]
 [ 320 3753    6]
 [ 161    4    6]
 [ 125 3440    4]
 [  90    2    4]
 [  87    4    4]
 [ 107    5    5]
 [  71    5    4]
 [  34    4    4]
 [ 102    6    1]
 [ 106    5    3]
 [2470    3    4]
 [2473    4    3]
 [2469    3    4]
 [2469    4    4]
 [2468    3    4]
 [2468    3    4]
 [2468    3    4]
 [2467    3    4]
 [2465    3    4]
 [2468    3    4]
 [2483    

In [0]:
# saving NPX and NPY numpy arrays
X_LOC = 'drive/My Drive/Self Driving/XTRAIN.npy'
Y_LOC = 'drive/My Drive/Self Driving/YTRAIN.npy'

np.save(X_LOC, NPX)
np.save(Y_LOC, NPY)